# frozen_string_literal: true

require "singleton"

module RuVim
  class Error < StandardError; end
  class CommandError < Error; end
end

require_relative "ruvim/version"
require_relative "ruvim/command_invocation"
require_relative "ruvim/display_width"
require_relative "ruvim/keyword_chars"
require_relative "ruvim/text_metrics"
require_relative "ruvim/clipboard"
require_relative "ruvim/lang/base"
require_relative "ruvim/lang/markdown"
require_relative "ruvim/lang/ruby"
require_relative "ruvim/lang/json"
require_relative "ruvim/lang/scheme"
require_relative "ruvim/lang/diff"
require_relative "ruvim/highlighter"
require_relative "ruvim/context"
require_relative "ruvim/buffer"
require_relative "ruvim/window"
require_relative "ruvim/editor"
require_relative "ruvim/command_registry"
require_relative "ruvim/ex_command_registry"
require_relative "ruvim/git/blame"
require_relative "ruvim/git/status"
require_relative "ruvim/git/diff"
require_relative "ruvim/git/log"
require_relative "ruvim/git/branch"
require_relative "ruvim/git/commit"
require_relative "ruvim/git/link"
require_relative "ruvim/git/handler"
require_relative "ruvim/global_commands"
require_relative "ruvim/dispatcher"
require_relative "ruvim/keymap_manager"
require_relative "ruvim/command_line"
require_relative "ruvim/input"
require_relative "ruvim/terminal"
require_relative "ruvim/rich_view"
require_relative "ruvim/lang/tsv"
require_relative "ruvim/lang/csv"
require_relative "ruvim/screen"
require_relative "ruvim/config_dsl"
require_relative "ruvim/config_loader"
require_relative "ruvim/app"
require_relative "ruvim/cli"
